# ASP.NET Core (.NET Framework)

trigger:
- main

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

pool:
  vmImage: 'windows-latest'
          
#       pool:
#         vmImage: $(imageName)

# strategy:
  # maxParallel: 3
  # matrix:
    # linux:
      # imageName: "ubuntu-latest"
    # mac:
      # imageName: "macOS-latest"
    # windows:
      # imageName: "windows-latest"

stages:
- stage: configureNugetAndBuildVS
  displayName: 'Build and Test Calculator'
  jobs: 
  - job: Build
    displayName: 'Configure Nuget and Build VS'
    steps:
      - task: NuGetToolInstaller@1
      - task: NuGetCommand@2
        inputs:
          restoreSolution: '$(solution)'
      - task: VSBuild@1
        inputs:
          solution: '$(solution)'
          msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'
  - job: Test
    displayName: 'Test Solution'
    steps:
      - task: VSTest@2
        inputs:
          testAssemblyVer2: |
            **\SpecFlowCalculator.Specs.dll
            !**\obj\**
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'
      - task: SpecFlowPlus@0
        inputs:
          projectFilePath: '$(System.DefaultWorkingDirectory)'
          projectLanguage: 'en'


